[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/ourownstory/neural_prophet/blob/master/example_notebooks/autoregression_yosemite_temps.ipynb)

# NBeats

This is a NBeats model module usage example. We implemented this model under the same API as NeuralProphet, for easy comparison of the results of NeuralProphet and SOTA models

We used as the base the implementation of NBeats from Pytorch Forecasting library. The model parameters are inherited automatically from the dataset structure, if from_dataset is set to True
For more detail on hyperparameters, please follow https://github.com/jdb78/pytorch-forecasting/blob/master/pytorch_forecasting/models/nbeats/__init__.py

In [ ]:
# install NeuralProphet from our repository
!pip install git+https://github.com/adasegroup/neural_prophet.git # may take a while

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from neuralprophet import NBeats
import pandas as pd

In [3]:
if 'google.colab' in str(get_ipython()):
    data_location = "https://raw.githubusercontent.com/adasegroup/neural_prophet/master/"
else:
    data_location = "../"

df = pd.read_csv(data_location + "example_data/yosemite_temps.csv")
df.head(3)
freq = '5min'

df = df.iloc[:1000]

In [193]:
m = NBeats(
        context_length = 150,
        prediction_length = 1,
        batch_size = None,
        epochs = 100,
        num_gpus = 0,
        patience_early_stopping = 10,
        early_stop = True,
        weight_decay=1e-2,
        learning_rate=3e-2,
        auto_lr_find=False,
        num_workers=3,
    )

In [194]:
m.fit(df.iloc[:-10], freq = freq)

WARNING - (py.warnings._showwarnmsg) - /Users/polina/.conda/envs/neural_prophet/lib/python3.7/site-packages/pandas/core/indexing.py:1676: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(ilocs[0], value, pi)

GPU available: False, used: False
TPU available: False, using: 0 TPU cores

  | Name            | Type       | Params
-----------------------------------------------
0 | loss            | MASE       | 0     
1 | logging_metrics | ModuleList | 0     
2 | net_blocks      | ModuleList | 1.8 M 
-----------------------------------------------
1.8 M     Trainable params
0         Non-trainable params
1.8 M     Total params
7.322     Total estimated model params size (MB)


Training: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

Validating: 0it [00:00, ?it/s]

SmoothL1Loss       MAE        MSE  SmoothL1Loss_val   MAE_val    MSE_val
0       6.198810  6.680655  76.175812          1.984398  2.441608  10.738672
1       1.495792  1.924352   7.416574          2.680520  3.180520  11.725144
2       1.038097  1.449940   3.971019          1.879793  2.345236   8.275595
3       0.842117  1.240759   2.852894          1.773558  2.239368   7.001941
4       0.627208  1.012027   1.818587          0.369869  0.701508   0.906012
5       0.608245  0.983793   1.724628          0.647796  1.022959   1.916453
6       0.489341  0.859040   1.275362          0.118067  0.398166   0.236483
7       0.370829  0.706616   0.991996          0.354424  0.663990   0.807281
8       0.432706  0.789142   1.120317          0.577993  1.021858   1.317486
9       0.479071  0.840852   1.246951          0.235968  0.546071   0.519624
10      0.333175  0.677785   0.790623          0.483152  0.893286   1.088850
11      0.451290  0.816991   1.205486          0.098519  0.334871   0.201779
12      0.424250  0.775740   1.085298          0.232112  0.622556   0.466812
13      0.271399  0.591050   0.614247          0.402897  0.836305   0.830393
14      0.249884  0.553718   0.598610          0.201699  0.537462   0.416677
15      0.246511  0.546564   0.569679          0.256062  0.590387   0.585083
16      0.242986  0.537177   0.566016          0.441607  0.820165   1.129949
17      0.366634  0.702797   0.947922          0.145843  0.449065   0.297284
18      0.260680  0.569562   0.598330          0.303941  0.589159   0.687991
19      0.260531  0.570894   0.620133          0.243974  0.542317   0.560167
20      0.235309  0.527583   0.568504          0.161553  0.455442   0.347950
21      0.266028  0.567022   0.665505          0.124618  0.366069   0.267597

In [195]:
future = m.make_future_dataframe(df, freq, periods=5, n_historic_predictions=100)

Number of forecast steps is defined by n_forecasts. Adjusted to 1.


In [196]:
import numpy as np

In [197]:
future

ds    y  time_idx  series
0   2017-05-03 14:30:00  7.1       750       0
1   2017-05-03 14:35:00  7.5       751       0
2   2017-05-03 14:40:00  7.7       752       0
3   2017-05-03 14:45:00  7.8       753       0
4   2017-05-03 14:50:00  8.2       754       0
..                  ...  ...       ...     ...
246 2017-05-04 11:00:00  8.2       996       0
247 2017-05-04 11:05:00  8.2       997       0
248 2017-05-04 11:10:00  8.2       998       0
249 2017-05-04 11:15:00  8.1       999       0
250 2017-05-04 11:20:00  8.1      1000       0

[251 rows x 4 columns]

In [ ]:
150 
на 150 мы предсказываем 1 исторические 20
на 150 -- 2
---
100-20 раз предсказываем историю 


In [205]:
forecast = m.predict(future)

WARNING - (py.warnings._showwarnmsg) - /Users/polina/.conda/envs/neural_prophet/lib/python3.7/site-packages/pandas/core/indexing.py:1738: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value[:, i].tolist(), pi)



In [206]:
forecast.iloc[149:]

ds     y      yhat1  residual1
149 2017-05-04 02:55:00  14.8        NaN        NaN
150 2017-05-04 03:00:00  14.4  14.585771   0.185771
151 2017-05-04 03:05:00  14.1  14.298700   0.198700
152 2017-05-04 03:10:00  13.8  14.028207   0.228207
153 2017-05-04 03:15:00  13.6  13.749867   0.149867
..                  ...   ...        ...        ...
246 2017-05-04 11:00:00   8.2   8.459127   0.259127
247 2017-05-04 11:05:00   8.2   8.444792   0.244792
248 2017-05-04 11:10:00   8.2   8.443011   0.243011
249 2017-05-04 11:15:00   8.1   8.441652   0.341652
250 2017-05-04 11:20:00   NaN   8.415902        NaN

[102 rows x 4 columns]

In [117]:
forecast.iloc[-10:]

ds   y  yhat1  yhat2  yhat3  yhat4  yhat5  yhat6  yhat7  \
260 2017-05-04 12:10:00 NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
261 2017-05-04 12:15:00 NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
262 2017-05-04 12:20:00 NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
263 2017-05-04 12:25:00 NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
264 2017-05-04 12:30:00 NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
265 2017-05-04 12:35:00 NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
266 2017-05-04 12:40:00 NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
267 2017-05-04 12:45:00 NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
268 2017-05-04 12:50:00 NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
269 2017-05-04 12:55:00 NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

     yhat8  ...  yhat11  yhat12  yhat13  yhat14  yhat15  yhat16  yhat17  \
260    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
261    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
262    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
263    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
264    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
265    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
266    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
267    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
268    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   
269    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN     NaN   

     yhat18  yhat19  yhat20  
260     NaN     NaN     NaN  
261     NaN     NaN     NaN  
262     NaN     NaN     NaN  
263     NaN     NaN     NaN  
264     NaN     NaN     NaN  
265     NaN     NaN     NaN  
266     NaN     NaN     NaN  
267     NaN     NaN     NaN  
268     NaN     NaN     NaN  
269     NaN     NaN     NaN  

[10 rows x 22 columns]

In [118]:
result = forecast

In [120]:
first_part

ds     y  yhat1  yhat2  yhat3  yhat4  yhat5  yhat6  \
0   2017-05-03 14:30:00   7.1    NaN    NaN    NaN    NaN    NaN    NaN   
1   2017-05-03 14:35:00   7.5    NaN    NaN    NaN    NaN    NaN    NaN   
2   2017-05-03 14:40:00   7.7    NaN    NaN    NaN    NaN    NaN    NaN   
3   2017-05-03 14:45:00   7.8    NaN    NaN    NaN    NaN    NaN    NaN   
4   2017-05-03 14:50:00   8.2    NaN    NaN    NaN    NaN    NaN    NaN   
..                  ...   ...    ...    ...    ...    ...    ...    ...   
145 2017-05-04 02:35:00  16.3    NaN    NaN    NaN    NaN    NaN    NaN   
146 2017-05-04 02:40:00  16.0    NaN    NaN    NaN    NaN    NaN    NaN   
147 2017-05-04 02:45:00  15.6    NaN    NaN    NaN    NaN    NaN    NaN   
148 2017-05-04 02:50:00  15.2    NaN    NaN    NaN    NaN    NaN    NaN   
149 2017-05-04 02:55:00  14.8    NaN    NaN    NaN    NaN    NaN    NaN   

     yhat7  yhat8  ...  yhat11  yhat12  yhat13  yhat14  yhat15  yhat16  \
0      NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
1      NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
2      NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
3      NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
4      NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
..     ...    ...  ...     ...     ...     ...     ...     ...     ...   
145    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
146    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
147    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
148    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
149    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

     yhat17  yhat18  yhat19  yhat20  
0       NaN     NaN     NaN     NaN  
1       NaN     NaN     NaN     NaN  
2       NaN     NaN     NaN     NaN  
3       NaN     NaN     NaN     NaN  
4       NaN     NaN     NaN     NaN  
..      ...     ...     ...     ...  
145     NaN     NaN     NaN     NaN  
146     NaN     NaN     NaN     NaN  
147     NaN     NaN     NaN     NaN  
148     NaN     NaN     NaN     NaN  
149     NaN     NaN     NaN     NaN  

[150 rows x 22 columns]

ds     y  yhat1  yhat2  yhat3  yhat4  yhat5  yhat6  \
150 2017-05-04 03:00:00  14.4    NaN    NaN    NaN    NaN    NaN    NaN   
151 2017-05-04 03:05:00  14.1    NaN    NaN    NaN    NaN    NaN    NaN   
152 2017-05-04 03:10:00  13.8    NaN    NaN    NaN    NaN    NaN    NaN   
153 2017-05-04 03:15:00  13.6    NaN    NaN    NaN    NaN    NaN    NaN   
154 2017-05-04 03:20:00  13.6    NaN    NaN    NaN    NaN    NaN    NaN   
..                  ...   ...    ...    ...    ...    ...    ...    ...   
265 2017-05-04 12:35:00   NaN    NaN    NaN    NaN    NaN    NaN    NaN   
266 2017-05-04 12:40:00   NaN    NaN    NaN    NaN    NaN    NaN    NaN   
267 2017-05-04 12:45:00   NaN    NaN    NaN    NaN    NaN    NaN    NaN   
268 2017-05-04 12:50:00   NaN    NaN    NaN    NaN    NaN    NaN    NaN   
269 2017-05-04 12:55:00   NaN    NaN    NaN    NaN    NaN    NaN    NaN   

     yhat7  yhat8  ...  yhat11  yhat12  yhat13  yhat14  yhat15  yhat16  \
150    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
151    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
152    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
153    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
154    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
..     ...    ...  ...     ...     ...     ...     ...     ...     ...   
265    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
266    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
267    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
268    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   
269    NaN    NaN  ...     NaN     NaN     NaN     NaN     NaN     NaN   

     yhat17  yhat18  yhat19  yhat20  
150     NaN     NaN     NaN     NaN  
151     NaN     NaN     NaN     NaN  
152     NaN     NaN     NaN     NaN  
153     NaN     NaN     NaN     NaN  
154     NaN     NaN     NaN     NaN  
..      ...     ...     ...     ...  
265     NaN     NaN     NaN     NaN  
266     NaN     NaN     NaN     NaN  
267     NaN     NaN     NaN     NaN  
268     NaN     NaN     NaN     NaN  
269     NaN     NaN     NaN     NaN  

[120 rows x 22 columns]

In [123]:
y_pred

array([[29, 23, 40, ...,  1, 80, 93],
       [28, 27, 93, ..., 98, 74, 70],
       [45, 66, 51, ..., 67,  1, 30],
       ...,
       [16, 93, 50, ..., 79, 68, 65],
       [77, 47, 96, ..., 96, 91, 33],
       [66, 98, 26, ..., 30,  3, 88]])

In [137]:
y_pred = np.random.randint(1, 100, (10, 3))

In [138]:
y_pred

array([[71,  5, 28],
       [97, 96, 28],
       [11, 17, 34],
       [40, 11, 14],
       [ 7, 25, 63],
       [90, 37, 54],
       [50, 13, 60],
       [49, 65, 92],
       [ 6, 93,  6],
       [27, 68, 11]])

In [150]:
y_pred_padded = np.pad(y_pred, 2)[2:,2:-2]
np.vstack([np.roll(y_pred_padded[:, i], i, axis = 0) for i in range(y_pred_padded.shape[1])]).T

In [151]:
y_pred_padded

array([[71,  5, 28],
       [97, 96, 28],
       [11, 17, 34],
       [40, 11, 14],
       [ 7, 25, 63],
       [90, 37, 54],
       [50, 13, 60],
       [49, 65, 92],
       [ 6, 93,  6],
       [27, 68, 11],
       [ 0,  0,  0],
       [ 0,  0,  0]])

In [152]:
np.vstack([np.roll(y_pred_padded[:, i], i, axis = 0) for i in range(y_pred_padded.shape[1])]).T

array([[71,  0,  0],
       [97,  5,  0],
       [11, 96, 28],
       [40, 17, 28],
       [ 7, 11, 34],
       [90, 25, 14],
       [50, 37, 63],
       [49, 13, 54],
       [ 6, 65, 60],
       [27, 93, 92],
       [ 0, 68,  6],
       [ 0,  0, 11]])

In [105]:
100 + 20 + 5

125

In [34]:
forecast

ds    y     yhat1 residual1
0   2017-05-03 14:30:00  7.1      None      None
1   2017-05-03 14:35:00  7.5      None      None
2   2017-05-03 14:40:00  7.7      None      None
3   2017-05-03 14:45:00  7.8      None      None
4   2017-05-03 14:50:00  8.2      None      None
..                  ...  ...       ...       ...
250 2017-05-04 11:20:00  NaN  8.125137       NaN
251 2017-05-04 11:25:00  NaN  8.072654       NaN
252 2017-05-04 11:30:00  NaN  8.031872       NaN
253 2017-05-04 11:35:00  NaN  8.009538       NaN
254 2017-05-04 11:40:00  NaN  8.011885       NaN

[255 rows x 4 columns]

In [ ]:
forecast.iloc[-15:]

In [ ]:
f = m.plot(forecast.iloc[-100:])